task:
  -init: |
       python -m venv todoapp-venv
       source todoapp-vevn/bin/activate
       pip install --upgrade pip wheel setuptools
       pip install -r requirements.txt
       python manage.py migrate
  -comand: |
       source todoapp-vevn/bin/activate
       python manage.py runserver

  ports:
     - port: 8000
       visibility: private 
       onOpen: open-preview 
